name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compilar
        run: cargo build --release

      - name: Publicar release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv target/release/Wyvern wyvern-linux-x86_64
          gh release create "$GITHUB_REF_NAME" \
            wyvern-linux-x86_64 \
            --generate-notes